[build]
builder = "NIXPACKS"
buildCommand = "npm install --include=dev && npm run build:frontend && npm install --prefix backend && npx prisma generate --schema=backend/prisma/schema.prisma"

[deploy]
startCommand = "node backend/server.js"
healthcheckPath = "/api/services"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
