[build]
builder = "NIXPACKS"
buildCommand = "npm install && npm install --prefix backend && npx prisma generate --schema=backend/prisma/schema.prisma && npm run build:frontend"

[deploy]
startCommand = "node backend/server.js"
healthcheckPath = "/api/services"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
